matrix:
  include:
    - os: linux
      language: android
      licenses:
        - "android-sdk-preview-license-52d11cd2"
        - "android-sdk-license-.+"
        - "google-gdk-license-.+"
      android:
        components:
          # Uncomment the lines below if you want to
          # use the latest revision of Android SDK Tools
          # - tools
          # - platform-tools

          # The BuildTools version used by your project
          - build-tools-28.0.2
          # The SDK version used to compile your project
          - android-28

          - extra-android-support
          - extra-google-m2repository
          - extra-android-m2repository

      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid

      before_install:
        - yes | sdkmanager "platforms;android-27"

      before_script:
        - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
        - unzip -qq gradle-3.5-bin.zip
        - export GRADLE_HOME=$PWD/gradle-3.5
        - export PATH=$GRADLE_HOME/bin:$PATH
        - git clone https://github.com/flutter/flutter.git -b alpha --depth 1
      script:
        - ./flutter/bin/flutter packages get
        - ./flutter/bin/flutter -v build apk

    - os: osx
      language: generic
      osx_image: xcode10
      before_script:
        # - pip install six
        - brew update
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - git clone https://github.com/flutter/flutter.git -b alpha --depth 1
      script:
        - ./flutter/bin/flutter packages get
        - ./flutter/bin/flutter -v build ios --no-codesign

cache:
  directories:
    - $HOME/.pub-cache
